### ISSUE TITLE
Add word descriptions

### ISSUE THREAD

**Issue by ManiacDC** [ManiacDC/TypingAid#34]
May be related to #18.

May you make it with suggestion in 2 column-listview? Column 1 is the suggested word. Column 2 is the meaning of this word in another language. So when we type, we can learn vocabulary at once.
 
Please help me to make this.
Thanks so lot!

**Comment by mayouly** [comment]
Waiting for this issue. Please running it!

**Comment by ManiacDC** [comment]
Starting work on this:
https://github.com/ManiacDC/TypingAid/commit/de6848c3189de8301723b61ab663d21f92eaf17c

**Comment by ManiacDC** [comment]
Code to display descriptions added:
https://github.com/ManiacDC/TypingAid/commit/03378dba11f5ee0ad2af2276d39bd8b922505eba

**Comment by ManiacDC** [comment]
I'm probably going to skip the listview... maybe that could be a separate issue.

There's an outstanding issue regarding the length of the contents of the autocomplete box. I'll need to truncate the autocomplete strings.

**Comment by ManiacDC** [comment]
I have fixed the listbox so it now will truncate the values it tries to display if they are too long.
https://github.com/ManiacDC/TypingAid/commit/10f80ee86e0212d811675f41303ba0ff75fd40cf

**Comment by mayouly** [comment]
Good job! Waiting the perfect issue. Thanks for your efforts

**Comment by ManiacDC** [comment]
Added a "Max width in pixels" setting and now add an ellipsis to truncated values:
https://github.com/ManiacDC/TypingAid/commit/3f70548672d4c6b9d5b62ca33afb1bb4c2323b8a

I also plan on making changes for word descriptions to have a better separator... maybe column aligned or tabbed (at least for fixed width fonts).

**Comment by ManiacDC** [comment]
https://github.com/ManiacDC/TypingAid/commit/b1b105a2722a69aca1df9942658f7d4799b4d8e6
When using Fixed Width fonts, added columns for word descriptions

**Comment by ManiacDC** [comment]
https://github.com/ManiacDC/TypingAid/releases/tag/v2.22.0.0

**Comment by mayouly** [comment]
Thanks a lot!

**Comment by ManiacDC** [comment]
You're welcome!
