### ISSUE TITLE
Allow learned words to appear before static words

### ISSUE THREAD

**Issue by ManiacDC** [ManiacDC/TypingAid#35]
Add an option to have the learned words automatically suggested above the wordlist words.

Should wordlist words be ranked too?

**Comment by Skrell** [comment]
yes they should :)

**Comment by ManiacDC** [comment]
https://github.com/ManiacDC/TypingAid/commit/480dbe1f94abad5b8cb1025da08e2ec86d26973d

**Comment by ManiacDC** [comment]
@Skrell , was the "yes they should" in response to ranking Wordlist words?

**Comment by Skrell** [comment]
I'm not sure I 100% understand your question.....this suggestion really only applied to putting the learned words above the regular dictionary words, however, in general yes i'd like to see wordlist words ranked too by frequency of use if that's what you're asking?

**Comment by ManiacDC** [comment]
In my original post I had asked (I didn't even remember asking this):
"Should wordlist words be ranked too?"

You made a response:
"yes they should :)"

I wasn't sure if your post was in response to my question above, or the issue itself:
"Allow learned words to appear before static words"

**Comment by Skrell** [comment]
It WAS in reference to your question.  :)

**Comment by ManiacDC** [comment]
OK, thanks! I think I'll make a separate issue out of that.

**Comment by ManiacDC** [comment]
Submitted as https://github.com/ManiacDC/TypingAid/issues/46

**Comment by Skrell** [comment]
Is this code ready to take?  https://github.com/ManiacDC/TypingAid/commit/480dbe1f94abad5b8cb1025da08e2ec86d26973d

**Comment by ManiacDC** [comment]
Yep! Go ahead and give it a shot.

**Comment by Skrell** [comment]
works perfectly!! release it!  :)

**Comment by ManiacDC** [comment]
Great, thanks! It'll be in the next release. :)
