### ISSUE TITLE
Suggestions appears on top left corner of window

### ISSUE THREAD

**Issue by danielo515** [ManiacDC/TypingAid#38]
Hello,

I really like this script, but it does not work as I expect. I expect it to appear under the mouse cursor. But instead the suggestions appears on the top left corner of the active window. Why does this happen? I'm on a multi window environment if that does matter.

Very cool script indeed.

**Comment by ManiacDC** [comment]
Hi Daniel, are you experiencing this in all programs (for example, try notepad)? Or just some (like firefox or chrome)?

If it's just some, TypingAid is unable to detect the caret position in certain programs, like FireFox, Chrome, or OpenOffice. A workaround called a "Helper Window" has been created to help deal with this. You can open it manually by hitting Ctrl-Shift-H, or you can have it open based on which window you're in by changing the following settings in Preferences.ini:
HelperWindowProgramExecutables
HelperWindowProgramTitles

Let me know...

**Comment by danielo515** [comment]
Hello @ManiacDC 

I checked your code, and I found that the problem was about the A_CaretX and A_CaretY on certain windows, as you said. I asked on ahk github and this is a known issue :-1:  Then I realized that there were some "helping window" but I did not noticed how that thing works. Now I'm using it to write this message thanks to your explanation. Looks like a rudimentary solution. I would prefer to use the mouse position as an alternative. Is this even possible? I though the helper window would appear automagically.

**Comment by ManiacDC** [comment]
That should be a viable alternative. I'll have to add a new setting for it.

The helper window appears automatically if you've added the program you're using to HelperWindowProgramExecutables or HelperWindowProgramTitles.

**Comment by danielo515** [comment]
> The helper window appears automatically if you've added the program you're using to HelperWindowProgramExecutables or HelperWindowProgramTitles.

Ok, I'll try it out. I did not see this information at any place.

Regarding the mouse alternative I can confirm it works fairly well. I use clipjump and some of my scripts uses that approach too and most of the times the mouse is very close to where you are writing.

Thank you!

**Comment by ManiacDC** [comment]
There was actually code in place to do this (draw the listbox at the mouse position). It was just... broken. I found it while doing some code cleanup. I've fixed this code in the SQLite branch, and it will be in the next release.

**Comment by ManiacDC** [comment]
This has been fixed with 2.20.0

**Comment by danielo515** [comment]
What do you mean with fixed exactly?
It is working properly for browsers now or it is properly using the mouse position as backup?

Regards

**Comment by ManiacDC** [comment]
It is properly using the mouse position as backup. There's nothing I can do about it not detecting the cursor position, that's a bug in the applications - they aren't reporting the cursor position to Windows.
