### ISSUE TITLE
Readme file is incorrectly rendered

### ISSUE THREAD

**Issue by insanetesterftw** [ManiacDC/TypingAid#42]
Your readme file is not correctly rendered on github. We see text and, i suppose, markdown markup. Perhaps you should change the extension to *.md?

**Comment by ManiacDC** [comment]
It's (a form of?) BBCode. It's just the contents of the OP here:
http://www.autohotkey.com/board/topic/49517-typingaid-v2195-word-autocompletion-utility/

I would recommend reading it there. I just tried changing the extension to .md, but it actually made it worse.

I'm closing this for now, but if you feel strongly about this, please comment and I'll look into maintaining 2 readme files. I did find a BBCode to markdown converter that might work.
