### ISSUE TITLE
word list files as a function of application

### ISSUE THREAD

**Issue by shev72** [ManiacDC/TypingAid#69]
it would be really nice if we could  associate specific word lists with specific applications.  For example when I am using outlook, there are some specific substirutions I would like to use.  but these are not applicable when I am using Word.

Wordlists as a function of application are particularly useful in conjunction with the recently added |t| and |d|  options (translate/define) which considerably enhance the power of typing aid.  The issue I am running  into is that as a function of my context (applications), most of my wordlist is not relevant, particuarly for |t| and |d| uses.

**Comment by ManiacDC** [comment]
This is a duplicate of:
https://github.com/ManiacDC/TypingAid/issues/32
