### ISSUE TITLE
Suggestion: Option to suppress word learning or predictions when in password fields

### ISSUE THREAD

**Issue by wolispace** [ManiacDC/TypingAid#73]

**Comment by ManiacDC** [comment]
Please see the setting "Sub-strings to not learn". Thanks!

**Comment by wolispace** [comment]
Yes that will work, but it does expose some of the password/s in plain text to anyone who can view my my settings.  Its a good start tho. 
Thanks

**Comment by ManiacDC** [comment]
Yes, it leaves a (hopefully) tiny bit of the password exposed. If you have some other recommendation, I'm all ears. Thanks!

**Comment by wolispace** [comment]
If we can detect which field (if any) we are in, but something tells me there is no reliable way, so the Sub-strings to ignore is a good solution.

**Comment by ManiacDC** [comment]
Yes, there's not a good way - especially in most browsers where TypingAid can't even detect the caret position. Thanks!
