### ISSUE TITLE
Suggestion: simplify the DLL files

### ISSUE THREAD

**Issue by wolispace** [ManiacDC/TypingAid#75]
Just one exe and one dll would be ideal (one set for 32bit, another for 64 bit), without the need for sub folders.

I tried deleting the 32bit exe and the dll in the starting location, then moving the dll from x64 into the same folder as the 64bit exe but it complained.

Can this be done now (remove all 32bit files that are of no use?)

Thanks

**Comment by ManiacDC** [comment]
Both exe's allow those who don't know what 32 vs 64 bit is to just run "TypingAid.exe" and let the program take care of the rest, so the dual exe will remain.

You can delete the 32 bit dll and exe file, but the 64bit sqlite dll needs to remain in the x64 folder.

Is there some problem that having a subfolder is causing?

**Comment by wolispace** [comment]
Good plan keeping things simple for users.

My personal reason is quite trivial, I just like wonderful tools like this to be as portable as possible, which in my mind is one exe and any dlls in the same folder. 

So to void reliance on specifically named sub-folders, I have ditched the 64bit files :-)

Seems to work ok in Win10 so nothing to worry about :-)

**Comment by ManiacDC** [comment]
The 64 bit doesn't give much benefit. Maybe a minor performance increase. Using the 32 bit version is just fine.
