### ISSUE TITLE
Suggestion: next word prediction feature 

### ISSUE THREAD

**Issue by diallobakary4** [ManiacDC/TypingAid#95]
like with [Swift key here ](https://www.youtube.com/watch?v=JZ3cX3EWE6s) or [here ](https://vrann.shinyapps.io/next-word-prediction/)

**Comment by ManiacDC** [comment]
Thanks! This is a duplicate of the below...
for non-learned words:
https://github.com/ManiacDC/TypingAid/issues/19
for learned words:
https://github.com/ManiacDC/TypingAid/issues/20
