### ISSUE TITLE
Is it possible to show wordlist next to typing cursor?

### ISSUE THREAD

**Issue by ozgurerdogan** [ManiacDC/TypingAid#98]
Is it possible to show wordlist next to typing cursor instead of mouse cursor? So I do not have to look for where mouse cursor is :)

**Comment by ManiacDC** [comment]
It already does this; however, certain applications, such as Chrome, do not provide the mouse cursor information to the program. For these, it will display next to the mouse pointer.

**Comment by ozgurerdogan** [comment]
My word list is only shown at mouse cursor and i donot see any option to have it display at typing cursor.

**Comment by ManiacDC** [comment]
Yes, it doesn't give an option. Either the application you are typing in reports the cursor position, or it doesn't. If it doesn't, the wordlist will show at the mouse cursor.

If you try it in a different application, like notepad, you'll find that it pops up at the typing cursor.
